### ISSUE TITLE
mathematics in reflection operator

### ISSUE THREAD

**Issue by corcra** [amarshah/complex_RNN#2]
Hi there, thanks for making your code public! I have been translating it to TensorFlow as an exercise and have therefore been reading it quite carefully. 

I'm a little confused by some of the mathematics in the reflection function `times_reflection` (https://github.com/amarshah/complex_RNN/blob/master/models.py#L49). Basically, I'm either making a mistake in my own calculations, I didn't understand something, or the code is not quite right. So, apologies in advance for how long this is, I'm trying to be comprehensive.

As I understand it, this function is applying the typical reflection operator in a complex vector _v_, e.g. on an input vector _h_:
 ![](https://dl.dropboxusercontent.com/u/1333033/latex/2_01.png)

At the end of the above-mentioned function, there is:

```
output = T.inc_subtensor(output[:, :n_hidden], - 2. / vstarv * (a + b))
output = T.inc_subtensor(output[:, n_hidden:], - 2. / vstarv * (d - c))
```

(where `vstarv` is the squared norm of _v_)

So I conclude that
![](https://dl.dropboxusercontent.com/u/1333033/latex/2_02.png)
(let's call this **equation 1**)

Doing a bit of expanding: (sorry for ugly LaTeX)
![](https://dl.dropboxusercontent.com/u/1333033/latex/2_03.png)

Simplifying the appearance of this expression by rewriting the inner product terms (removing the dot and the vector symbol) to remind us these are just real scalars at this point, and gathering real and imaginary components:

![](https://dl.dropboxusercontent.com/u/1333033/latex/2_04.png)

So now we have:

![](https://dl.dropboxusercontent.com/u/1333033/latex/2_05.png)
(let's call this **equation 2**)

Looking back at the code, we have

```
a = T.outer(input_re_reflect_re - input_im_reflect_im, reflect_re)
b = T.outer(input_re_reflect_im + input_im_reflect_re, reflect_im)
c = T.outer(input_re_reflect_re - input_im_reflect_im, reflect_im)
d = T.outer(input_re_reflect_im + input_im_reflect_re, reflect_re)
```

LaTeXing these up for easier comparison (the `outer`, I think, should just be accounting for the fact that the first dimension of these `input_...` variables is the batch size, so this is all batched, which shouldn't matter for these calculations), and remembering that `input` is _h_ and `reflect` is _v_ in my notation:

![](https://dl.dropboxusercontent.com/u/1333033/latex/2_06.png)

Putting it together to get expressions for _a+b_ and _d-c_...

![](https://dl.dropboxusercontent.com/u/1333033/latex/2_07.png)

According to **equation 1** the right hand side here should equal the right hand side of **equation 2**, but... it doesn't seem to. What is going on? Some of the signs are wrong. Did I make a mistake?

I thought that perhaps the operator in question is _not_ the typical reflection operator, but is in fact
![](https://dl.dropboxusercontent.com/u/1333033/latex/2_08.png)
(the dagger there denoting the _conjugate_ transpose)
... but this _also_ seems not to reproduce the expressions in the code [proof left to the reader]. I might also have made an error checking that, but my question would then be: if that is the intended operator, why conjugate transpose? Where does this operator come from?

**Comment by martinarjovsky** [comment]
A unitary matrix is defined as a matrix that has UU\* = U*U = I with \* the conjugate transpose. If you take the transpose instead of the conjugate transpose in your vector the transformation is not unitary.

Reflection by a complex vector uses therefore the dagger operator (or the conjugate transpose if you want to call it like that). Are you positive the code isn't doing that? I'll check the math in detail later.

**Comment by corcra** [comment]
Thanks for the quick response. I see, of course the operator should be unitary! Does one still have the geometric interpretation of a rotation in this case, though?

Regarding the maths: to get the expression for the unitary version, it _should_ (I think!) be sufficient to just change the sign of the imaginary part of the reflection (_v_im_) whenever it appeared in a dot product. Assuming the rest of the algebra is correct, this should result in: (compare with **equation 2**)

![](https://dl.dropboxusercontent.com/u/1333033/latex/2_09.png)

... which still doesn't reproduce the expressions for `d-c` and `a+b`! What am I missing here?

**Comment by corcra** [comment]
I figured it out btw, your code is actually implementing the operator
![codecogseqn](https://cloud.githubusercontent.com/assets/4471845/18352005/d12b0794-75dc-11e6-9f0a-1d3edd6c1815.gif)
... which is also unitary, and just a reflection in the conjugate of _v_, so it's all good.
